# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30, null=True)),
                ('phone', models.CharField(default=None, max_length=12, null=True)),
                ('email', models.CharField(default=None, max_length=30, null=True)),
                ('profession', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
    ]
